Drop windows binary
As ci job errored with:
src\_extensions.c(208): error C2143: syntax error: missing ';' before '*'
    src\_extensions.c(208): error C2065: 'in1': undeclared identifier
    src\_extensions.c(208): error C2100: you cannot dereference an operand of type 'int'
    src\_extensions.c(208): error C2065: 'in2': undeclared identifier
    src\_extensions.c(208): error C2100: you cannot dereference an operand of type 'int'
    src\_extensions.c(208): error C2065: 'out': undeclared identifier
    src\_extensions.c(208): error C2100: you cannot dereference an operand of type 'int'
    src\_extensions.c(226): error C2065: 'in1': undeclared identifier
    src\_extensions.c(226): error C2146: syntax error: missing ')' before identifier '_complex'
    src\_extensions.c(226): error C2059: syntax error: ')'
    src\_extensions.c(226): error C2297: '*': not valid as right operand has type 'void *'
    src\_extensions.c(227): error C2065: 'in2': undeclared identifier
    src\_extensions.c(227): error C2146: syntax error: missing ')' before identifier '_complex'
    src\_extensions.c(227): error C2059: syntax error: ')'
    src\_extensions.c(227): error C2297: '*': not valid as right operand has type 'void *'
    src\_extensions.c(228): error C2065: 'out': undeclared identifier
    src\_extensions.c(228): error C2146: syntax error: missing ')' before identifier '_complex'
    src\_extensions.c(228): error C2059: syntax error: ')'
    src\_extensions.c(228): error C2297: '*': not valid as right operand has type 'void *'
    src\_extensions.c(232): error C2065: 'out': undeclared identifier
    src\_extensions.c(232): error C2109: subscript requires array or pointer type
    src\_extensions.c(232): error C2065: 'in1': undeclared identifier
    src\_extensions.c(232): error C2109: subscript requires array or pointer type
    src\_extensions.c(232): error C2198: '_Dcomplex conj(_Dcomplex)': too few arguments for call
    src\_extensions.c(232): error C2065: 'in2': undeclared identifier
    src\_extensions.c(232): error C2109: subscript requires array or pointer type